### ISSUE TITLE
Cannot download checkpoints

### ISSUE THREAD

**Issue by voducman** [Markfryazino/wav2lip-hq#5]

**Comment by voducman** [comment]
Please check the link for downloading checkpoints. I can not see any checkpoints with names: face_segmentation.pth, esrgan_max.pth

**Comment by freecui** [comment]
I  just find esrgan_yunying.pth, but there isn't face_segmentation.pth.
![1628659274(1)](https://user-images.githubusercontent.com/8288975/128973783-f2ec2ac6-9cda-45d6-a716-89dda7b0ae7a.jpg)

**Comment by freecui** [comment]
I should down face_segmentation.ph from face-parsing.PyTorch repository , am I right?

**Comment by jageshmaharjan** [comment]
@freecui maybe you are looking for this:
https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth
or
!wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" -O "face_detection/detection/sfd/s3fd.pth"
and you file is at face_detection/detection/sfd/s3fd.pth
or
https://drive.google.com/open?id=154JgKpzCPW82qINcVieuPH3fZ2e0P812
from https://github.com/zllrunning/face-parsing.PyTorch

**Comment by xugaoxiang** [comment]
> 

Last face segmentation model link is not available. pls update it.
